### Creating Numpy Arrays

In [1]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [5]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [6]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [7]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [2]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [4]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Atributes

In [5]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [6]:
# ndim
a3.ndim

3

In [7]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [8]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [9]:
# itemsize
a3.itemsize

4

In [10]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


In [11]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [12]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [14]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [15]:
# vector operations
# arithmetic
a1 ** a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

### Array function

In [16]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[46., 89., 98.],
       [16.,  2., 29.],
       [79., 17., 41.]])

In [17]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([ 58144.,   3026., 116522.])

In [18]:
# mean/median/std/var
np.var(a1,axis=1)

array([514.88888889, 121.55555556, 651.55555556])

In [19]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.90178835,  0.86006941, -0.57338187],
       [-0.28790332,  0.90929743, -0.66363388],
       [-0.44411267, -0.96139749, -0.15862267]])

In [20]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [21]:
# log and exponents
np.exp(a1)

array([[9.49611942e+19, 4.48961282e+38, 3.63797095e+42],
       [8.88611052e+06, 7.38905610e+00, 3.93133430e+12],
       [2.03828107e+34, 2.41549528e+07, 6.39843494e+17]])

In [22]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[54., 34., 18.],
       [25.,  5., 65.]])

### Indexing and Slicing

In [23]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [24]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
a2[1,0]

4

In [27]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [28]:
a3[1,1,0]

6

In [29]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a1[2:5:2]

array([2, 4])

In [31]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [33]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [34]:
a2[1,::3]

array([4, 7])

In [35]:
a2[0,:]

array([0, 1, 2, 3])

In [36]:
a2[:,2]

array([ 2,  6, 10])

In [37]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [38]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [39]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [40]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [41]:
a3[0,1,:]

array([3, 4, 5])