In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,100,15)
a

array([12, 12, 75, 63, 81, 28, 62,  1, 43, 64, 30, 35, 50, 25, 96])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[19, 62, 49, 16],
       [23, 84, 41, 31],
       [ 1, 51, 33, 23],
       [87, 50, 73, 60],
       [50, 41, 13, 61],
       [77,  2, 70,  4]])

In [4]:
np.sort(a)[::-1]

array([96, 81, 75, 64, 63, 62, 50, 43, 35, 30, 28, 25, 12, 12,  1])

<h1> np.append </h1>
<p> The numpy.append() appends values along the mentioned axis at the end of the array<p>
<a href ="https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html"> For docmentation click here </a>

In [5]:
# code
np.append(a,200)

array([ 12,  12,  75,  63,  81,  28,  62,   1,  43,  64,  30,  35,  50,
        25,  96, 200])

In [6]:
b

array([[19, 62, 49, 16],
       [23, 84, 41, 31],
       [ 1, 51, 33, 23],
       [87, 50, 73, 60],
       [50, 41, 13, 61],
       [77,  2, 70,  4]])

In [7]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[19.        , 62.        , 49.        , 16.        ,  0.20283447],
       [23.        , 84.        , 41.        , 31.        ,  0.88066304],
       [ 1.        , 51.        , 33.        , 23.        ,  0.73210231],
       [87.        , 50.        , 73.        , 60.        ,  0.38195876],
       [50.        , 41.        , 13.        , 61.        ,  0.33927512],
       [77.        ,  2.        , 70.        ,  4.        ,  0.25273842]])

<h2> np.concatenate </h2>
 <p> numpy.concatenate() function concatenate a sequence of arrays along an existing axis. <p>

<a href="https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html"> For documentation click here</a>

In [10]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [11]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

<h3> np.unique </h3>
<p> With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method. </p>
<p><a href ="https://numpy.org/doc/stable/reference/generated/numpy.unique.html/"> For Documentation click here</a></p>

In [13]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [14]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

-With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

<a href="https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html">For documentation click Here</a>

In [15]:
# code
a.shape

(15,)

In [16]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [17]:
np.expand_dims(a,axis=1)

array([[12],
       [12],
       [75],
       [63],
       [81],
       [28],
       [62],
       [ 1],
       [43],
       [64],
       [30],
       [35],
       [50],
       [25],
       [96]])

### np.where
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.htm

In [18]:
a

array([12, 12, 75, 63, 81, 28, 62,  1, 43, 64, 30, 35, 50, 25, 96])

In [19]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 2,  3,  4,  6,  9, 14], dtype=int64),)

In [20]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([12, 12,  0,  0,  0, 28,  0,  1, 43,  0, 30, 35, 50, 25,  0])

In [21]:
np.where(a%2 == 0,0,a)

array([ 0,  0, 75, 63, 81,  0,  0,  1, 43,  0,  0, 35,  0, 25,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [22]:
np.argmax(a)

14

In [23]:
b

array([[19, 62, 49, 16],
       [23, 84, 41, 31],
       [ 1, 51, 33, 23],
       [87, 50, 73, 60],
       [50, 41, 13, 61],
       [77,  2, 70,  4]])

In [24]:
np.argmax(b,axis=0)

array([3, 1, 3, 4], dtype=int64)

In [25]:
np.argmax(b,axis=1)

array([1, 1, 1, 0, 3, 0], dtype=int64)

In [26]:
# np.argmin
np.argmin(a)

7

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [27]:
np.cumsum(a)

array([ 12,  24,  99, 162, 243, 271, 333, 334, 377, 441, 471, 506, 556,
       581, 677])

In [28]:
b

array([[19, 62, 49, 16],
       [23, 84, 41, 31],
       [ 1, 51, 33, 23],
       [87, 50, 73, 60],
       [50, 41, 13, 61],
       [77,  2, 70,  4]])

In [29]:
np.cumsum(b,axis=1)

array([[ 19,  81, 130, 146],
       [ 23, 107, 148, 179],
       [  1,  52,  85, 108],
       [ 87, 137, 210, 270],
       [ 50,  91, 104, 165],
       [ 77,  79, 149, 153]])

In [30]:
np.cumsum(b)

array([  19,   81,  130,  146,  169,  253,  294,  325,  326,  377,  410,
        433,  520,  570,  643,  703,  753,  794,  807,  868,  945,  947,
       1017, 1021])

In [31]:
# np.cumprod
np.cumprod(a)

array([        12,        144,      10800,     680400,   55112400,
       1543147200, 1185845888, 1185845888, -548234368, -727261184,
       -342999040,  879935488, 1047101440,  407732224,  487587840])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [32]:
np.percentile(a,50)

43.0

In [33]:
np.median(a)

43.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [35]:
np.histogram(a,bins=[0,50,100])

(array([8, 7], dtype=int64), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [37]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [38]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([30, 50])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [39]:
np.flip(a)

array([96, 25, 50, 35, 30, 64, 43,  1, 62, 28, 81, 63, 75, 12, 12])

In [40]:
b

array([[19, 62, 49, 16],
       [23, 84, 41, 31],
       [ 1, 51, 33, 23],
       [87, 50, 73, 60],
       [50, 41, 13, 61],
       [77,  2, 70,  4]])

In [41]:
np.flip(b,axis=1)

array([[16, 49, 62, 19],
       [31, 41, 84, 23],
       [23, 33, 51,  1],
       [60, 73, 50, 87],
       [61, 13, 41, 50],
       [ 4, 70,  2, 77]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [44]:
np.put(a,[0,1],[110,530])

In [42]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [45]:
np.delete(a,[0,2,4])

array([530,  63,  28,  62,   1,  43,  64,  30,  35,  50,  25,  96])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [46]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [47]:
np.intersect1d(m,n)

array([3, 4, 5])

In [48]:
np.setdiff1d(n,m)

array([6, 7])

In [49]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [50]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [51]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 63, 75, 28, 62, 25, 43, 64, 30, 35, 50, 25, 75])

In [52]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [53]:
# 19. np.count_nonzero

In [54]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [55]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5